### ISSUE TITLE
Native builds failing 

### ISSUE THREAD

**Issue by paulrutter** [blueconic/node-oom-heapdump#28]
See https://github.com/blueconic/node-oom-heapdump/actions/runs/5643075202

@spmiller any idea whats causing this to fail? Might be that the github action scripts need adjusting, since we didn’t release for a while.

Let me know

**Comment by spmiller** [comment]
Hi @paulrutter, it looks like the runner has switched to python3 whereas the code in node-gyp is expecting to use python2. I suspect this could be resolved by upgrading the node-gyp version, like we do in the Windows build. It looks like the Windows build was automatically cancelled though so I can't say for sure.

I'll try updating it in my fork and send a PR if it works.

**Comment by paulrutter** [comment]
Ok great, thanks for your quick response!
Let me know if i need to review something.

**Comment by paulrutter** [comment]
@spmiller any update on this one?

**Comment by spmiller** [comment]
Hi @paulrutter, so sorry for not updating you back in July. I recall writing an update in here but it obviously didn't send.

The root of the issue seems to be that Node12 has been removed from Github actions, and some of the tasks are now running on Node16:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

If I change the config file to only prebuild versions for Node16+, everything is green again.

I could submit a patch to do this if you like? It doesn't drop support for the older versions, it just doesn't prebuild them.

**Comment by paulrutter** [comment]
That sounds great @spmiller, please do :)

**Comment by paulrutter** [comment]
This on is fixed.
