### ISSUE TITLE
Prebuilt binaries failing for Node 22 on Windows

### ISSUE THREAD

**Issue by paulrutter** [blueconic/node-oom-heapdump#33]
See https://github.com/blueconic/node-oom-heapdump/actions/runs/8830424770

@spmiller when you have time, could you check why node 22 doesn't work?

**Comment by spmiller** [comment]
Hi @paulrutter , I'm away on holiday this week but should be able to take a look first thing next week. It looks like the Windows build can't find npm?!

**Comment by paulrutter** [comment]
Great! No hurry.
Yes, somehow nom cannot be found with 22.x

**Comment by spmiller** [comment]
Hi @paulrutter, it's lucky that "first thing next week" turned into Thursday because there is an upstream issue that has had some patched pushed recently:
https://github.com/nodejs/node/issues/52682

By the time you read this they may have cut a new NodeJS release, but I would suggest that we can't build with Node 22 on Windows until the linked issue is resolved.

Good thing Node 22 isn't LTS eh!

**Comment by paulrutter** [comment]
Then we can wait for that to be merged!

**Comment by paulrutter** [comment]
22.1 seems to have fixed it :) thanks for checking it out @spmiller

See https://github.com/blueconic/node-oom-heapdump/commit/e36551dbd5401047480b248bd64bd82f4881fe9c

**Comment by paulrutter** [comment]
I will republish as 3.2.3 tomorrow

**Comment by paulrutter** [comment]
https://github.com/nodejs/nan/issues/968

**Comment by paulrutter** [comment]
https://github.com/blueconic/node-oom-heapdump/actions/runs/9102048245

**Comment by paulrutter** [comment]
https://github.com/blueconic/node-oom-heapdump/releases/tag/3.2.3
